import type { Metadata } from "next";
import { EB_Garamond, Faustina, Geist, Geist_Mono, Lexend, Slabo_13px } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";

import LoganFive from "next/font/local";

const loganFive = LoganFive({
    src: "../../public/fonts/LoganFiveW00Bold.ttf",
    variable : "--font-logan"
})

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  // subsets: ["latin"],
});

const lexend = Lexend({
    variable: "--font-lexend",
  subsets : ["latin"]
})


export const metadata: Metadata = {
  title: "SkillBridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${loganFive.variable} ${ebGaramond.variable} ${lexend.className}  antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster richColors/>
        </ThemeProvider>
      </body>
    </html>
  );
}
