import type { Metadata } from "next";
import { Faustina, Geist, Geist_Mono, Lexend, Slabo_13px } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";

import LoganFive from "next/font/local";

const loganFive = LoganFive({
    src: "../../public/fonts/LoganFiveW00Bold.ttf",
    variable : "--font-logan"
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lexend = Lexend({
    variable: "--font-lexend",
  subsets : ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const slabo = Slabo_13px({
  weight : "400"
})

export const metadata: Metadata = {
  title: "SkillBridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${loganFive.variable} ${lexend.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster richColors/>
        </ThemeProvider>
      </body>
    </html>
  );
}
